# ***Data Types and Structures Questions***

##**1. What are data structures, and why are they important?**

* Data structures are specialized formats for organizing, storing, and
accessing collections of data. They provide efficient ways to manage information based on its characteristics and intended use.

* **Why are they important?**

  -- Choosing the right data structure significantly impacts the efficiency and performance of your program.

  -- Well-chosen data structures can:

    Simplify data manipulation (adding, removing, modifying elements)

    Optimize searching and sorting operations

    Conserve memory usage

## **2.  Explain the difference between mutable and immutable data types with examples?**

**In Python, Mutable data types** can be modified after creation (like lists
and dictionaries), while **immutable data types** cannot (like strings and tuples).

**Mutable Data Types:**
  These data types allow you to change their values after they are created, without creating a new object.

* **Examples:**

**Lists:** my_list = [1, 2, 3] can be modified by adding, removing, or changing elements.

**Dictionaries:** my_dict = {'a': 1, 'b': 2} can be modified by adding, removing, or changing key-value pairs.

**Sets:** my_set = {1, 2, 3} can be modified by adding or removing elements.

* **Example:**

  my_list = [1, 2, 3]

  my_list[0] = 4  # Modifying the first element

  print(my_list)  # Output: [4, 2, 3]


**Immutable Data Types:**
These data types cannot be changed after they are created, meaning any operation that appears to modify them actually creates a new object with the modified value.

* **Examples:**

**Strings:** my_string = "hello" cannot be changed directly; any modification creates a new string object.

**Tuples:** my_tuple = (1, 2, 3) cannot be changed after creation.

**Numbers (int, float, etc.):** my_number = 5 cannot be changed; any operation creates a new number object.

* **Example:**

my_string = "hello"

my_string[0] = 'w'  //This will raise an error because strings are immutable

new_string = my_string + " world" # Creating a new string

print(new_string) # Output: hello world

##**3.  What are the main differences between lists and tuples in Python?**

The key difference between lists and tuples in Python lies in their mutability: lists are mutable (can be changed after creation), while tuples are immutable (cannot be changed).

##**4.  Describe how dictionaries store data.**

A Python dictionary is a data structure that stores the value in key: value pairs. Values in a dictionary can be of any data type and can be duplicated, whereas keys can't be repeated and must be immutable.

**Example:**
d = {1: 'Apple', 2: 'Banana', 3: 'Pear'}

print(d)

**Output:**

{1: 'Apple', 2: 'Banana', 3: 'Pear'}

##**5.  Why might you use a set instead of a list in Python?**

A Set is preffered over List because sets cannot have multiple occurrences of the same element, it makes sets highly useful to efficiently remove duplicate values from a list or tuple and to perform common math operations like unions and intersections.

## **6.  What is a string in Python, and how is it different from a list?**

![image.png]()

##**7.  How do tuples ensure data integrity in Python?**

Tuples are immutable to ensure that their contents remain constant throughout their lifecycle, guaranteeing data integrity and reliability. This immutability allows tuples to be used as keys in dictionaries and elements in sets, as they can be hashed.

##**8.  What is a hash table, and how does it relate to dictionaries in Python?**

**What is a Hash Table?**

* A hash table is a data structure that stores key-value pairs.

* It uses a hash function to determine the storage location (index) of a key within an array (or "buckets").

* This allows for efficient (average O(1) time complexity) retrieval, insertion, and deletion of data.

**How it relates to Python Dictionaries:**

* Python dictionaries are implemented using hash tables.

* When you create a dictionary, Python uses a hash function to map the keys to indices within an internal array (or "buckets").

* This allows you to access values in a dictionary very quickly, based on their keys.

##**9.  Can lists contain different data types in Python?**

* Lists with mixed data types are Python lists that contain elements of different data types.
* This means that a single list can hold a combination of integers, floats, strings, booleans, and even other complex data structures like lists, tuples, or dictionaries.

## **10.  Explain why strings are immutable in Python.**

Since immutable objects cannot change their value, Python can optimize memory usage. Reusing the same immutable object across the program whenever possible reduces memory overhead.

## **11. What advantages do dictionaries offer over lists for certain tasks?**

Dictionaries excel over lists in Python for tasks requiring fast lookups and storing data as key-value pairs, offering efficient retrieval and organization of information.

* **Fast Lookups:**

Dictionaries use a hash table (or hash map) internally, allowing for near-instantaneous retrieval of values based on their keys, while lists require sequential searching.

* **Key-Value Association:**

Dictionaries store data as key-value pairs, making it easy to associate data logically and retrieve specific information using a unique key.

* **Flexibility:**

Dictionaries can store any data type as values, including other dictionaries or lists, providing flexibility in structuring complex data.

* **Memory Efficiency:**

Dictionaries only store the key-value pairs, unlike lists which store all elements sequentially, potentially saving memory when dealing with large datasets.

* **Built-in Methods:**

Python provides a rich set of built-in methods for manipulating dictionaries, such as get(), keys(), values(), and items(), simplifying common operations.

* **Mapping Relationships:**

Dictionaries are well-suited for mapping relationships between items, such as storing user data (name, age, email) where the names act as keys and the other data as values.

* **Readability:**

Dictionaries make code more readable when dealing with key-value pairs, as the association between data is explicit.

* **Unordered:**

Dictionaries are unordered, meaning the order of key-value pairs is not preserved, which can be a disadvantage in certain situations where order is important.

## **12. Describe a scenario where using a tuple would be preferable over a list.**

* Tuples are generally faster and more memory-efficient than lists, making them better for fixed collections, especially as dictionary keys or when iteration speed is crucial.

* Tuples are often used to store coordinates in 2D or 3D space. It is advantageous to use a tuple to store coordinates because coordinates are essentially an ordered pair or set of values that are used to represent a specific location in space.

## **13.  How do sets handle duplicate values in Python?**

In set, duplicate items are not allowed. If items appear multiple times, only one will be recognized in the set. The items in a set are unordered. The order of the set changes every time it is used.

## **14.  How does the “in” keyword work differently for lists and dictionaries?**

* The in operator tells you whether something appears as a key in the dictionary. It returns two values True or False.

* The in operator uses different algorithms for lists and dictionaries. For lists, it uses a search algorithm. As the list gets longer, the search time gets longer in direct proportion.

* For dictionaries, Python uses an algorithm called a hashtable that has a remarkable property: the in operator takes about the same amount of time no matter how many items there are in a dictionary.

## **15. Can you modify the elements of a tuple? Explain why or why not.**


No, you cannot directly modify the elements of a tuple in Python because tuples are immutable, meaning their contents cannot be changed after creation.

**Here's why:**

* **Immutability:** Tuples are designed to be a fixed, ordered collection of items, and allowing modification would violate this fundamental principle.

* **Data Integrity:** Immutability helps ensure data integrity by preventing accidental or unintended changes to the tuple's contents.

* **Efficiency**: Because tuples are immutable, the Python interpreter can optimize their storage and access, leading to potentially faster performance.

* **Alternative:** If you need a mutable sequence, use a list instead.

**Example:**

    my_tuple = (1, 2, 3)
    # Attempting to modify a tuple element will raise a TypeError
    # my_tuple[0] = 4  # This will cause an error

## **16.  What is a nested dictionary, and give an example of its use case?**

* A nested dictionary is a dictionary where the values are themselves dictionaries, allowing for hierarchical data organization.

* A use case is representing an organizational chart, where departments (keys) map to dictionaries containing employee IDs and names (values).

**Example:**

    company_org_chart = {
      "Marketing": {
        "ID234": "Jane Smith",
        "ID567": "John Doe"
      },
      "Sales": {
        "ID123": "Bob Johnson",
        "ID122": "David Lee"
      },
      "Engineering": {
        "ID303": "Radhika Potlapally",
        "ID321": "Maryam Samimi"
      }
    }

**In this example:**

* company_org_chart is the main dictionary.

* The keys are department names ("Marketing", "Sales", "Engineering").

* The values are dictionaries containing employee information (ID and name).

* To access an employee's name, you would use double brackets:

  company_org_chart["Sales"]["ID122"] would return "David Lee".

## **17. Describe the time complexity of accessing elements in a dictionary.**

The time complexity of retrieving a value by its key in a dictionary is O(1). This is because dictionaries use a hash table internally which allows constant time lookup.

## **18.  In what situations are lists preferred over dictionaries?**

* A list can store any data type. In contrast, keys in the dictionary can be of any immutable data type, and values can be of any data type. Lists perform faster for ordered operations like sorting, while dictionaries perform faster for lookup operations.

* For quick data look-ups, configurations, or caches, favor dictionaries. For ordered collections and sequence operations, such as maintaining a stack or queue, lists are more suitable.

## **19. Why are dictionaries considered unordered, and how does that affect data retrieval?**

Dictionaries are considered unordered because they don't inherently maintain the order in which key-value pairs are inserted, unlike lists or tuples. This lack of inherent order means you can't rely on the order of keys when iterating or retrieving data.

## **20. Explain the difference between a list and a dictionary in terms of data retrieval.**

In data retrieval, lists access elements by their numerical index (starting from 0), while dictionaries access elements by their unique keys, offering potentially faster lookups for large datasets.

![image.png]()

# ***Practical Questions***

In [1]:
# 1. Write a code to create a string with your name and print it.

name = "Bhavisha"
name

'Bhavisha'

In [12]:
# 2. Write a code to find the length of the string "Hello World".

str1 = "Hello World"
print(str1)
len(str1)

Hello World

11

In [13]:
# 3. Write a code to slice the first 3 characters from the string "Python Programming".

str2 = "Python Programming"
print(str2)
str2[0:3]

Python Programming

'Pyt'

In [14]:
# 4. Write a code to convert the string "hello" to uppercase.

str3 = "hello"
print(str3)
str3.upper()

hello

'HELLO'

In [15]:
# 5. Write a code to replace the word "apple" with "orange" in the string "I like apple".

string = "I like apple"
new_string = string.replace("apple", "orange")
new_string

'I like orange'

In [16]:
# 6. Write a code to create a list with numbers 1 to 5 and print it.

my_list = list(range(1, 6))
my_list

[1, 2, 3, 4, 5]

In [17]:
# 7. Write a code to append the number 10 to the list [1, 2, 3, 4]

my_list = [1, 2, 3, 4]
my_list.append(10)
my_list

[1, 2, 3, 4, 10]

In [18]:
# 8. Write a code to remove the number 3 from the list [1, 2, 3, 4, 5]

my_list = [1, 2, 3, 4, 5]
my_list.remove(3)
my_list

[1, 2, 4, 5]

In [19]:
# prompt: 9. Write a code to access the second element in the list ['a', 'b', 'c', 'd'].

my_list = ['a', 'b', 'c', 'd']
second_element = my_list[1]
second_element

'b'

In [20]:
# 10. Write a code to reverse the list [10, 20, 30, 40, 50].

my_list = [10, 20, 30, 40, 50]
reversed_list = my_list[::-1]
reversed_list

[50, 40, 30, 20, 10]

In [21]:
# 11. Write a code to create a tuple with the elements 100, 200, 300 and print it.

my_tuple = (100, 200, 300)
my_tuple

(100, 200, 300)

In [ ]:
# 12. Write a code to access the second-to-last element of the tuple ('red', 'green', 'blue', 'yellow').

my_tuple = ('red', 'green', 'blue', 'yellow')
second_to_last_element = my_tuple[-2]
second_to_last_element

In [22]:
# 13. Write a code to find the minimum number in the tuple (10, 20, 5, 15).

my_tuple = (10, 20, 5, 15)
min_number = min(my_tuple)
min_number

5

In [23]:
# 14. Write a code to find the index of the element "cat" in the tuple ('dog', 'cat', 'rabbit').

my_tuple = ('dog', 'cat', 'rabbit')
index_of_cat = my_tuple.index('cat')
index_of_cat

1

In [ ]:
# 15. Write a code to create a tuple containing three different fruits and check if "kiwi" is in it.

# Create a tuple of fruits
fruits = ("apple", "banana", "orange")

# Check if "kiwi" is in the tuple
if "kiwi" in fruits:
  print("Kiwi is in the tuple.")
else:
  print("Kiwi is not in the tuple.")

In [24]:
# 16. Write a code to create a set with the elements 'a', 'b', 'c' and print it.

my_set = {'a', 'b', 'c'}
my_set

{'a', 'b', 'c'}

In [27]:
# 17. Write a code to clear all elements from the set {1, 2, 3, 4, 5}.

# Create a set
my_set = {1, 2, 3, 4, 5}

# Print the set with values
print(my_set)

# Clear all elements from the set
my_set.clear()

# Print the empty set
my_set

{1, 2, 3, 4, 5}

set()

In [29]:
# 18. Write a code to remove the element 4 from the set {1, 2, 3, 4}.

# Create a set
my_set = {1, 2, 3, 4}

# Print the set with values
print(my_set)

# Remove the element 4 from the set
my_set.remove(4)

# Print the updated set
my_set

{1, 2, 3, 4}

{1, 2, 3}

In [30]:
# 19. Write a code to find the union of two sets {1, 2, 3} and {3, 4, 5}.

# Create two sets
set1 = {1, 2, 3}
set2 = {3, 4, 5}

print(set1)
print(set2)

# Find the union of the two sets using the union() method
union_set = set1.union(set2)

# Print the union of the two sets
print("Union of set1 and set2:", union_set)

{1, 2, 3}
{3, 4, 5}
Union of set1 and set2: {1, 2, 3, 4, 5}

In [32]:
# 20. Write a code to find the intersection of two sets {1, 2, 3} and {2, 3, 4}.

s1 = {1, 2, 3}
s2 = {2, 3, 4}

print(s1)
print(s2)

# Find the intersection of the two sets using the intersection() method
intersection_set = s1.intersection(s2)

# Print the intersection of the two sets
print("Intersection of set1 and set2:", intersection_set)

{1, 2, 3}
{2, 3, 4}
Intersection of set1 and set2: {2, 3}

In [33]:
# 21. Write a code to create a dictionary with the keys "name", "age", and "city", and print it.

my_dictionary = {
    "name": "Bhavisha Parmar",
    "age": 28,
    "city": "Surat"
}

my_dictionary

{'name': 'Bhavisha Parmar', 'age': 28, 'city': 'Surat'}

In [34]:
# 22. Write a code to add a new key-value pair "country": "USA" to the dictionary {'name': 'John', 'age': 25}.

my_dict = {'name': 'John', 'age': 25}
print(my_dict)
my_dict['country'] = 'USA'
my_dict

{'name': 'John', 'age': 25}

{'name': 'John', 'age': 25, 'country': 'USA'}

In [35]:
# 23. Write a code to access the value associated with the key "name" in the dictionary {'name': 'Alice', 'age': 30}.

my_dictionary = {'name': 'Alice', 'age': 30}
name_value = my_dictionary['name']
name_value

'Alice'

In [38]:
# 24. Write a code to remove the key "age" from the dictionary {'name': 'Bob', 'age': 22, 'city': 'New York'}.

my_dict = {'name': 'Bob', 'age': 22, 'city': 'New York'}
print(my_dict)
del my_dict['age']
my_dict

{'name': 'Bob', 'age': 22, 'city': 'New York'}

{'name': 'Bob', 'city': 'New York'}

In [39]:
# 25. Write a code to check if the key "city" exists in the dictionary {'name': 'Alice', 'city': 'Paris'}.

my_dict = {'name': 'Alice', 'city': 'Paris'}

if 'city' in my_dict:
  print("The key 'city' exists in the dictionary.")
else:
  print("The key 'city' does not exist in the dictionary.")

The key 'city' exists in the dictionary.

In [40]:
# 26. Write a code to create a list, a tuple, and a dictionary, and print them all.

# Create a list
my_list = [1, 2, 3, 4, 5]

# Create a tuple
my_tuple = (6, 7, 8, 9, 10)

# Create a dictionary
my_dictionary = {"name": "Bhavisha", "age":28, "city": "Surat"}

# Print the list, tuple, and dictionary
print("List--->", my_list)
print("Tuple--->", my_tuple)
print("Dictionary--->", my_dictionary)

List---> [1, 2, 3, 4, 5]
Tuple---> (6, 7, 8, 9, 10)
Dictionary---> {'name': 'Bhavisha', 'age': 28, 'city': 'Surat'}

In [46]:
# 27. Write a code to create a list of 5 random numbers between 1 and 100, sort it in ascending order, and print the result.(replaced)

import random

# Create a list of 5 random numbers between 1 and 100
random_numbers = [random.randint(1, 100) for _ in range(5)]

# Print the random numbers list
print(random_numbers)

# Sort the list in ascending order
random_numbers.sort()

# Print the sorted list
random_numbers

[42, 36, 91, 70, 55]

[36, 42, 55, 70, 91]

In [47]:
# 28. Write a code to create a list with strings and print the element at the third index.

my_list = ["apple", "banana", "cherry", "date", "elderberry"]
print(my_list)
third_element = my_list[3]
third_element

['apple', 'banana', 'cherry', 'date', 'elderberry']

'date'

In [50]:
# 29. Write a code to combine two dictionaries into one and print the result.

dict1 = {'a': 1, 'b': 2}
dict2 = {'c': 3, 'd': 4}

print(dict1)
print(dict2)

combined_dict = {**dict1, **dict2}

combined_dict

{'a': 1, 'b': 2}
{'c': 3, 'd': 4}

{'a': 1, 'b': 2, 'c': 3, 'd': 4}

In [52]:
# 30. Write a code to convert a list of strings into a set.

my_list = ["apple", "banana", "cherry", "apple", "banana"]
print(my_list)

my_set = set(my_list)
my_set

['apple', 'banana', 'cherry', 'apple', 'banana']

{'apple', 'banana', 'cherry'}